image: docker

services:
  - docker:dind

build:
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose up -d

#before_script:
#  - composer install
#  - cp .env.example .env
#  - php artisan key:generate
#  - php artisan config:cache
#  - php artisan migrate
#  - php artisan db:seed

test:
  script:
    - docker-compose run php vendor/bin/phpunit --coverage-text --colors=never
