image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - dev
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - echo "$USER"
    - sudo docker-compose build
    - sudo docker-compose up -d
    - docker-compose run --user=gitlab-runner php composer install
    - docker-compose run --user=gitlab-runner php cp .env.example .env
    - docker-compose run --user=gitlab-runner php php artisan key:generate
    - docker-compose run --user=gitlab-runner php php artisan config:cache
    - docker-compose run --user=gitlab-runner php php artisan db:create
    - docker-compose run --user=gitlab-runner php php artisan migrate
    - docker-compose run --user=gitlab-runner php php artisan db:seed
  environment: production
  when: manual
