image: docker:stable

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - dev
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose build --no-cache
    - sudo docker-compose up -d
    - docker-compose run php composer install
    - docker-compose run php cp .env.example .env
    - docker-compose run php php artisan key:generate
    - docker-compose run php php artisan config:cache
    - sudo chown $USER:$USER -R .
#    - docker-compose run php php artisan db:create
#    - docker-compose run php php artisan migrate
#    - docker-compose run php php artisan db:seed
  environment: production
  when: manual
