before_script:
  - echo "Before script"
  - cd /var/www/html/
  - echo "Removing older releases"
  - find . -type d -mtime +3 -exec rm -rf {} +;
building:
  stage: build
  script:
    - rm -rf $CI_COMMIT_SHA/
    - git clone git@gitlab.com:splitapp/Splitit-backend.git $CI_COMMIT_SHA
    - cd $CI_COMMIT_SHA/
    - git checkout dev
    - composer install
    - cp .env.deploy .env
    - php artisan key:generate
    - php artisan db:create -v
    - php artisan migrate:fresh
    - php artisan db:seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    #- chown -R deployer:www-data /var/www/html/app/
    - find /var/www/html/$CI_COMMIT_SHA/ -type f -exec chmod 664 {} \;
    - find /var/www/html/$CI_COMMIT_SHA/ -type d -exec chmod 775 {} \;
    #- #chgrp -R www-data storage bootstrap/cache
    #- #chmod -R ug+rwx storage bootstrap/cache
testing:
  stage: test
  script:
    - cd $CI_COMMIT_SHA/
    - composer dump-autoload
    - php artisan cache:clear
    - php artisan config:clear
    - php ./vendor/bin/phpunit --coverage-text --colors=never
deploying:
  stage: deploy
  script:
    - rm -rf /var/www/html/app/
    - mv /var/www/html/$CI_COMMIT_SHA /var/www/html/app
    - cd /var/www/html/app/
    - php artisan apidoc:generate
    - php artisan telescope:install
    - php artisan migrate
    - echo "Deployed"
  when: manual
