image: tmaier/docker-compose:latest

services:
  - docker:dind

variables:
  DOCKER_COMPOSE: "docker-compose run -u 1000:1000 --rm"

before_script:
  - docker-compose --version

cache:
  untracked: true
  paths:
    - vendor/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - dev
    - master
  script:
    - sudo docker image prune -f
    - sudo docker-compose build
    - sudo docker-compose up -d
  after_script:
    - sudo chown $USER:$USER -R .

test:
  stage: test
  only:
    - dev
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - $DOCKER_COMPOSE php composer install
    - $DOCKER_COMPOSE php cp .env.example .env
    - $DOCKER_COMPOSE php php artisan key:generate
    - $DOCKER_COMPOSE php php artisan config:cache
    - $DOCKER_COMPOSE php composer dump-autoload
    - $DOCKER_COMPOSE php php artisan db:create -v
    - $DOCKER_COMPOSE php php artisan cache:clear
    - $DOCKER_COMPOSE php php artisan migrate -v
    - $DOCKER_COMPOSE php php artisan db:seed
  environment: production
  when: manual
