image: docker:stable

services:
  - docker:dind

stages:
  - test
  - deploy

default:
  before_script:
    - sudo chown $USER:$USER -R .

test:
  stage: test
  only:
    - dev
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose build
    - sudo docker-compose up -d
    - docker-compose exec -T php php composer install
    - docker-compose exec -T php cp .env.example .env
    - docker-compose exec -T php php artisan key:generate
    - docker-compose exec -T php artisan config:cache
    - docker-compose exec -T php artisan db:create -v
    - docker-compose exec -T php artisan migrate -v
    - docker-compose exec -T php artisan db:seed

  environment: production
  when: manual
