image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker-compose --version
  - sudo chown $USER:$USER -R ~/builds/

after_script:
  - sudo chown $USER:$USER -R ~/builds/

cache:
  untracked: true
  paths:
    - vendor/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - dev
    - master
  script:
    - sudo docker image prune -f
    - sudo docker-compose build
    - sudo docker-compose up -d

test:
  stage: test
  only:
    - dev
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - docker exec -it php composer install
    - docker exec -it php cp .env.example .env
    - docker exec -it php php artisan key:generate
    - docker exec -it php php artisan config:cache
    - docker exec -it php php artisan db:create -v
    - docker exec -it php php artisan migrate -v
    - docker exec -it php php artisan db:seed
    #- sudo chown $USER:$USER -R .

  environment: production
  when: manual
