image: docker

services:
  - docker:dind

build:
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d

#before_script:
#  - composer install
#  - cp .env.example .env
#  - php artisan key:generate
#  - php artisan config:cache
#  - php artisan migrate
#  - php artisan db:seed

test:
  cache:
    paths:
      - vendor/
  script:
    - docker-compose run php php vendor/bin/phpunit --coverage-text --colors=never
