version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - db
  php:
    environment:
      PHP_IDE_CONFIG: "serverName=docker-server"
    container_name: php
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/app:cached
      - ./docker/php/default.ini:/usr/local/etc/php/conf.d/default.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - db
      - web
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/log/nginx:cached
      - ./:/var/www/app:cached
    networks:
      - web
networks:
  db:
  web:
